### ISSUE TITLE
flashgot copyright notice

### ISSUE THREAD

**Issue by davidhedlund** [tikservices/html5-video-everywhere#19]
Fellow hacker.

IceCat is the GNU version of the Mozilla Firefox browser. IceCat comes with HTML5 Video Everywhere! inbuilt, an alternative to Flash player addons. Recently your software was added to the FSF's Free Software Directory: https://directory.fsf.org/wiki/HTML5_Video_Everywhere!

But there are a little problem I hope you can help us with. https://github.com/lejenome/html5-video-everywhere/blob/master/README.md says: "YouTube signature decoder code (data/flashgot-YouTubeSwf.js, lib/flashgot-YouTube.js) was copied from the GPL licenced flashgot extension with some code removed and other added code under the same licence.".

data/flashgot-YouTubeSwf.js does not have any copyright or license information in the top of file and there is no copy of the GPL alongside this file. Additionally, I do not know if other files interact with the flashgot-YouTubeSwf.js file in such a way that they would consittute a single combined work under the terms of the GNU GPL. If so, then the program as a whole would need to licensed under the terms of the GPL. I fyou could please update the header files and the license notices that would be greatly appreciated.

Thank you in advance.

**Comment by lejenome** [comment]
Thanks for your notice,
I added license information to `data/flashgot-YouTubeSwf.js`.

The MPL licensed `lib/youtube.js` (line 2 & 19) interact with GPL licensed `lib/flashgot-YouTube.js` which itself interacts with `data/flashgot-YouTubeSwf.js`. 
I added all other needed code to `lib/flashgot-YouTube.js' itself (25-40 and 478-535) to keep other files clean. Unneeded code is removed too.

If I still broke any license, I will dual license the extension under booth GPL and MPL.
