### ISSUE TITLE
[Facebook] Support videos on timeline

### ISSUE THREAD

**Issue by pocesar** [tikservices/html5-video-everywhere#23]
It doesn't seem to work on facebook, both in video page and on timeline. Anything else I should be doing for it to work? Tried disabling flash plugin and restarting to force it using the addon but no difference. In youtube it's working properly

**Comment by Mosrite** [comment]
For me, it works if I open videos in a new tab, but not in theater mode. It would be great if this could be fixed!

**Comment by lejenome** [comment]
the extension supports only `facebook.com/video.php?v=...` links. I didn't find a way to support other links yet:
- there is no custom fired event or a function called when their pop-up PhotoViewer dialog opens or new/more posts are loaded.
- Other solution is to add an event listener to mouse clicks on video posts thumbnail and replace them with the video player but in this case, the video url is not included on the timeline page code.

I will try again to find an other solution on next days.

**Comment by lejenome** [comment]
@pocesar the extension supports only `facebook.com/video.php?v=...` links. And there is an issue that causes the extension to fail injecting Firefox video player and requires reloading the page.

**Comment by pocesar** [comment]
couldn't it listen on popState? I have no idea how add-ons work though. single page applications use the history api extensively, so either listening to DOM changes + URL state should do the trick I guess

**Comment by lejenome** [comment]
@pocesar  I just released a new version that fixes an issue caused by some events firing on wrong order.
This should fix video not loading on `facebook.com/video.php?v=...` links.

Support for timeline and theater mode is not implemented yet.

**Comment by pocesar** [comment]
seems to be working now
