### ISSUE TITLE
Opt-out on specific sites (e.g. YouTube)

### ISSUE THREAD

**Issue by Hexcles** [tikservices/html5-video-everywhere#24]
Since YouTube starts to use HTML5 player for most videos on modern browsers by default (http://techcrunch.com/2015/01/27/youtube-goes-html5-flash-is-now-deader/) and I prefer the original YouTube HTML5 player, it would be good to provide a setting to disable the substitution on specific sites.

**Comment by lejenome** [comment]
There is a non-documented hidden option `extensions.html5-video-everywhere@lejenome.me.disable`

It accepts a comma-separated list of sites to disable their support.

To disable YouTube support: open `about:config` link and accept the warrning notice then search for `extensions.html5-video-everywhere@lejenome.me.disable` and set it to `youtube`.

**Comment by Hexcles** [comment]
Thank you! And could you consider adding this option to document or even to the configuration interface (a comma-separated text input is good enough).

Anyway, it works now. Cheers!
