### ISSUE TITLE
[YouTube] subtitles support

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [tikservices/html5-video-everywhere#31]
Is possible to add youtube subtitles support?

**Comment by lejenome** [comment]
Just added support to subtitles for YouTube. It's available on latest release on AMO.

You can choose subtitle for current video throw context menu or a preferred subtitle throw Add-on Manager interface. Booth methods depends if the subtitle language is available for the video.

Can you confirm it works right?

**Comment by Alessandro-Barbieri** [comment]
Ok, works for me, but i have to know the video have subtitles ...
Thank you much.

**Comment by lejenome** [comment]
I'm closing this issue as the non user friendly interface issue is tracked down on an other issue.
