### ISSUE TITLE
Is there any way to replace the url to https://u.f-q.me/watch?v=IpRzDu1Seqk ?

### ISSUE THREAD

**Issue by ARwMq9b6** [tikservices/html5-video-everywhere#34]
https://github.com/lejenome/html5-video-everywhere/commit/36cb361bf2d4ea5eb457b366e4b94670c6b89fc4

**Comment by sefsh** [comment]
Why?

**Comment by lejenome** [comment]
As long there is no strong reason to use third-party services, I'm not planning to add external services for security and privacy.
My YouTube signature decoder implementation based on flashgot code is not perfect yet. But I prefer to improve it instead of redirecting to https://u.f-c.me urls.
