### ISSUE TITLE
How do I turn on YouTube subtitles?

### ISSUE THREAD

**Issue by davidhedlund** [tikservices/html5-video-everywhere#37]
I do not find any option to turn on subtitles in HTML5 Video Everywhere! 0.2.30.

I've played videos in https://www.youtube.com/results?search_query=subtitle+movie but no text are shown in them.

How do I enable subtitles in YouTube?

**Comment by lejenome** [comment]
To enable subtitles for current video; right click on video player >
"Subtitles" > choose a subtitle lang from available languages.

To enable subtitles for every video, from addon settings on Addon manager
interace. set "Subtitles" value to a subtitle lang you want and it will be
selected every time you open a video on YT/vimeo that has a subtitle with same
lang.

Subtitles with unicode chars are not supported yet. A fix will follow later
today.

**Comment by davidhedlund** [comment]
I only get the context menu when I right click. There's no menu button in the player either.

How do I access it?

**Comment by davidhedlund** [comment]
Problem not solved.

**Comment by lejenome** [comment]
a new version is available now

**Comment by davidhedlund** [comment]
@lejenome It works!

**Comment by davidhedlund** [comment]
@lejenome But it does not work every time, see https://www.youtube.com/watch?v=4M9K5ccBadE for example.

**Comment by davidhedlund** [comment]
@lejenome This is the problem. "en" is pre-selected in the "Subtitle" list from the context menu or right mouse click, but nothing happens. If I now select "none" and then back to "en" then the subtitle appear.
