### ISSUE TITLE
Reuse ViewTubePlus code

### ISSUE THREAD

**Issue by lejenome** [tikservices/html5-video-everywhere#47]
ViewTubePlus is a UserScript alternative to Html5-video-everywhere with support for various sites.
http://userscripts-mirror.org/scripts/show/159658
https://heliotropium.it/ViewTubePlus.user.js

**Comment by flyingzebras** [comment]
This issue is a duplication of https://github.com/lejenome/html5-video-everywhere/issues/41 @lejenome. Please close it.

**Comment by davidhedlund** [comment]
@lejenome Thank you.
