### ISSUE TITLE
Please add About in video context menu

### ISSUE THREAD

**Issue by davidhedlund** [tikservices/html5-video-everywhere#49]
Some web browsers come with HTML5 Video Everywhere pre-installed but it is not always possible to locate it in the "Add-ons" list. Abrowser (part of Trisquel GNU/Linux) is a good example.

This makes it hard to know which version of HTML5 Videos Everywhere that is being used, a work around could be to add "About HTML5 Video Everywhere" in the context menu for videos.

YouTube HTML5 Video Player has "About the HTML5 Player" in the context menu when you mouse hover over videos.

**Comment by jdorn-eu** [comment]
Is there any reason why Abrowser would not show an installed add-on in the add-ons list?

**Comment by davidhedlund** [comment]
The point is that it should be possible to show which player is being used for each video. Some websites works with HTML5 Video Everywhere, some don't. @jeifour

**Comment by lejenome** [comment]
new item "About HTML5 Video Everywhere" on context menu added on latest release that shows a small window with some links and current addon version.

**Comment by flyingzebras** [comment]
@lejenome Yes, you can close this issue now. Thank you.
