### ISSUE TITLE
Please rename Youtube HTML5 Video Player

### ISSUE THREAD

**Issue by davidhedlund** [tikservices/html5-video-everywhere#51]
Youtube HTML5 Video Player (https://addons.mozilla.org/en-US/firefox/addon/youtube-html5-video-player/) is named after the exact same title as YouTube's integrated Youtube HTML5 Video Player, this is confusing.

Please rename "Youtube HTML5 Video Player" to "Youtube HTML5 Video Player-libre" or something that makes the name unique.

**Comment by lejenome** [comment]
Renamed to `Simple YouTube HTML5 Player`

**Comment by davidhedlund** [comment]
@lejenome Good name. Thanks.
