### ISSUE TITLE
How is Youtube HTML5 Video Player different from HTML5 Video Everywhere!?

### ISSUE THREAD

**Issue by davidhedlund** [tikservices/html5-video-everywhere#52]
What is the difference between?:
- Youtube HTML5 Video Player - https://addons.mozilla.org/en-US/firefox/addon/youtube-html5-video-player/ - Home page refer to https://github.com/lejenome/html5-video-everywhere
- HTML5 Video Everywhere! - https://addons.mozilla.org/en-US/firefox/addon/html5-video-everywhere/

**Comment by lejenome** [comment]
Just the same but with only Youtube support is enabled on YouTube HTML5 Video Player; Same code base and updated on same time, but different on a [static argument](https://github.com/lejenome/html5-video-everywhere/blob/master/Makefile#L4)

I will keep updating the old extension until more users switch to the new one.

**Comment by davidhedlund** [comment]
@lejenom Thank you.

**Comment by davidhedlund** [comment]
@lejenome "
Just the same but with only Youtube support is enabled on YouTube HTML5 Video Player; Same code base and updated on same time, but different on a static argument

I will keep updating the old extension until more users switch to the new one.
"

Can you please add that to the description in the addons.mozilla.org page?

**Comment by lejenome** [comment]
done

**Comment by davidhedlund** [comment]
@lejenome Thank you once again.
