### ISSUE TITLE
[Now part of Firefox 49.0] Repeat button in control bar

### ISSUE THREAD

**Issue by davidhedlund** [tikservices/html5-video-everywhere#53]
![html5-video-everywhere--repeat_button_request](https://cloud.githubusercontent.com/assets/6416073/7692185/66eb0d8c-fdc1-11e4-8821-2118543bb4d4.png)

The Firefox add-on Media loop is described as a "Menu item to control [HTML5] audio/video loop" - https://addons.mozilla.org/en-US/firefox/addon/media-loop/. Media loop can be used to repeat HTML5 videos on any website, not just YouTube.

Can you to implement Media loop in HTML5 Videos Everywhere! and a Repeat button that uses it in Control. Refer to the red marked repeat icon located bottom right at the above modified screenshot?

HTML5 Video Everywhere is currently part of GNU IceCat, if we add the repeat button there is a great chance that other developers add the repeat button to their web players.

**Comment by jdorn-eu** [comment]
My work-around right now: right click inspect the video element and add the loop argument to the tag.

**Comment by davidhedlund** [comment]
@jeifour "Inspect Element (Q)"?

Also, how do you add the loop argument?

**Comment by jdorn-eu** [comment]
@davidhedlund Yes, "Inspect Element (Q)" probably in an English version of Firefox.
Just double-click on the video tag and add an attribute by writing something like `loop="loop"`, then save this and close the dev tools. That particular video will now always loop, but you will have to do it everytime that you want to make videos loop. This works with every pure html5 video on the web btw.
Quick demo (sorry flv/mp4 video): https://a.pomf.se/fooocq.flv

**Comment by davidhedlund** [comment]
Thank you very much for taking your time with recordings and all @jeifour I'm new with Firebug and didn't know it was possible to edit on the fly.

**Comment by jomo** [comment]
There's actually a plugin for this called [Media Loop](https://addons.mozilla.org/en-US/firefox/addon/media-loop/?src=search):

![image](https://addons.cdn.mozilla.net/user-media/previews/full/38/38239.png)

**Comment by davidhedlund** [comment]
Thank you for helping me out dear @jomo, you made my day! I updated the lead by adding this great add-on. @jeifour please have a look.

**Comment by davidhedlund** [comment]
@lejenome I made a screenshot for you to better explain the feature request. By the way, can you please label this issue "Feature"?

**Comment by jdorn-eu** [comment]
I don't think your points get across any better if you keep spamming issue trackers, honestly. If the feature is so vital for you that you can't wait for proper answers of project maintainers, you're free to fork this repository; this add-on is free software after all.

**Comment by davidhedlund** [comment]
@jeifour I just asked him to label the issue.

**Comment by lejenome** [comment]
implemented on context menu and addon manager interface on lastest update.
Adding buttons to the player control bar depends on using an other video player implementation other than firefox default video player.

**Comment by davidhedlund** [comment]
@lejenome Is this issue submitted in the proper place?

**Comment by jomo** [comment]
I think this feature request should go towards Firefox, since this plugin just replaces custom players with Firefox' native HTML video player.

_(Or you just use the plugin I linked you to)_

**Comment by davidhedlund** [comment]
@lejenome I posted this enhancement in https://bugzilla.mozilla.org/show_bug.cgi?id=1168681

**Comment by davidhedlund** [comment]
It is great that repeat support for YT has been added. But it does not yet work in other websites like the add-on Media loop.

**Comment by lejenome** [comment]
fixed, will be included on next release

**Comment by davidhedlund** [comment]
@lejenome Please make sure that it do not interfere with Media loop. Enable/disable Media loop braked HTML5 Video Everywhere when I tested.

**Comment by lejenome** [comment]
support for video repeat on other sites is added on latest release

**Comment by flyingzebras** [comment]
@lejenome Not working in PornHub NETWORK sites: examples
- http://www.pornhub.com/view_video.php?viewkey=75327659
- http://www.tube8.com/anal/hardcore-anal-in-12-inch-white-cock/24354041/

**Comment by lejenome** [comment]
only sites supported by the extension. Porn sites are not supported yet.

**Comment by flyingzebras** [comment]
@lejenome Thank you for letting me know and thank you for adding this feature to other websites!

**Comment by davidhedlund** [comment]
@lejenome Media loop repeat HTML5 videos in all websites, is it possible to implement it in HTML5 Video Everywhere?

**Comment by lejenome** [comment]
Because the extension currently support only 6 websites. Adding just loop
support to other websites is not this extension job, you should use other
extension to add loop support for all sites.

**Comment by davidhedlund** [comment]
@lejenome Oh, I thought I used HTML5 Video Everywhere in all websites but I can figure that out now since you added About. Thanks.

**Comment by davidhedlund** [comment]
@lejenome Why do not HTML5 Video Everywhere live up to its name, why do the extension support only 6 websites?

**Comment by jomo** [comment]
because there are a lot of websites on the internet. Make a PR for sites you want supported?

**Comment by lejenome** [comment]
Websites support is tracked on milestones [1]. PR are welcome.

Some issues [2] are blocking support for new websites mainly MSE extension
support and flash player handling.

[1] https://github.com/lejenome/html5-video-everywhere/milestones
[2] https://github.com/lejenome/html5-video-everywhere/issues?q=is:open+is:issue+label:%22help+wanted%22

**Comment by davidhedlund** [comment]
@lejenome Interesting, thank you for the information. Where can I access Milestones from https://github.com/lejenome/html5-video-everywhere ?

**Comment by lejenome** [comment]
https://github.com/lejenome/html5-video-everywhere/milestones

**Comment by davidhedlund** [comment]
@lejenome Yes, I just wonder in which HTML pages its located too.

**Comment by jomo** [comment]
The [latest Firefox release](https://www.mozilla.org/en-US/firefox/49.0/releasenotes/) includes a loop option, see this beautiful screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/3585743/18708887/735ecbde-7ffd-11e6-82e1-1d153381f6ff.png)

Now there's two loop options, the one added by this plugin doesn't seem two work. I guess it can be removed?

**Comment by davidhedlund** [comment]
@jomo Aswome! - I actually [submitted this idea](https://bugzilla.mozilla.org/show_bug.cgi?id=1168681).
