### ISSUE TITLE
Critical: Background audio in YouTube

### ISSUE THREAD

**Issue by davidhedlund** [tikservices/html5-video-everywhere#54]
When I play this link: https://www.youtube.com/watch?v=6CmmwP970qg

I get the audio from the clip twice, the extra audio that start within 10 seconds when the video has started. If I pause the video I still hear the extra audio and this does not even go away if I click on another YouTube link on that page.

**Comment by jdorn-eu** [comment]
Can't reproduce on this video. Are you sure you aren't running any other add-ons or userscripts?

**Comment by davidhedlund** [comment]
I could not reproduce this either. I appears occasionally but it might be some other add-on. @jeifour
