### ISSUE TITLE
Consider global HTML5 video support

### ISSUE THREAD

**Issue by davidhedlund** [tikservices/html5-video-everywhere#56]
Why do not HTML5 Video Everywhere live up to its name, why do the extension support only 6 websites?

**Comment by lejenome** [comment]
Websites support is tracked on milestones [1]. PR are welcome.

Some issues [2] are blocking support for new websites mainly MSE extension
support and flash player handling.

[1] https://github.com/lejenome/html5-video-everywhere/milestones
[2] https://github.com/lejenome/html5-video-everywhere/issues?q=is:open+is:issue+label:%22help+wanted%22

**Comment by davidhedlund** [comment]
@lejenome There is no reference for [2]. Can you please add it?
