### ISSUE TITLE
youtube not showing comments or allowing votes

### ISSUE THREAD

**Issue by godfree2** [tikservices/html5-video-everywhere#58]
addon is not allowing voting or viewing comments

**Comment by drselump14** [comment]
same issue here

**Comment by vitusson** [comment]
I can confirm this. After trying out a lot of of preference settings in my FF, with no comment section, I switched off single add-ons, and it turned out to be the HTML5 one. 
Mozilla/5.0 (X11; Linux i686; rv:42.0) Gecko/20100101 Firefox/42.0 Iceweasel/42.0

**Comment by vitusson** [comment]
ah, now I see there's already a bug report https://github.com/lejenome/html5-video-everywhere/issues/20. Sorry, overlooked that one.

**Comment by lejenome** [comment]
duplicate of https://github.com/lejenome/html5-video-everywhere/issues/20
