### ISSUE TITLE
Urgent: YouTube HTML5 player start 2-3 seconds after  HTML5 Video Everywhere!

### ISSUE THREAD

**Issue by davidhedlund** [tikservices/html5-video-everywhere#62]
YouTube HTML5 player is used simultaneously as HTML5 Video Everywhere! in certain videos with a delay of 2-3 seconds. This makes HTML5 Video Everywhere! useless in GNU IceCat for the moment.

Example video that reproduce the error: https://www.youtube.com/watch?v=wKL0dOZ821s
HTML5 Video Everywhere! 0.2.38.1-signed (higher version not compatible with IceCat)
GNU IceCat 31.8.0 (based on Firefox ESR 31.8.0)

**Comment by lejenome** [comment]
This issue was fixed on latest release.
