### ISSUE TITLE
Question: Permissions

### ISSUE THREAD

**Issue by suedi** [tikservices/html5-video-everywhere#67]
I am trying to figure out how to set permissions for html5 to work with html5-video-everywhere
and icecat for an unprivilegied user.

I am on Arch Linux Derivative

in  /usr/lib/icecat/browser/extensions/html5-video-everywhere@lejenome.me/resources/html5-video-everywhere/lib

I see from error messages that I can fix by `chmod o+r *`
in the above directory.

Still I get error message 

``` bash
console.error: html5-video-everywhere: 
  Error opening input stream (invalid filename?)
```

And video is not playing

if I do 

```
chmod 777  /usr/lib/icecat/browser/extensions/html5-video-everywhere@lejenome.me -R
chown user:user -R /usr/lib/icecat/browser/extensions/html5-video-everywhere@lejenome.me
```

it starts, I don't want to give out more permissions than nescessary though.

Any leads what to change?

**Comment by lejenome** [comment]
It may be an error on your umask settings,
The most minimal permission are:
- folder: `rwx---r-x`  0705
- files: `rw----r--` 0604

but the recommanded permissions are:
- folders: `rwxr-xr-x` 0755
- files: `rw-r--r--` 0644

These commands should fix the issue:

``` sh
sudo chown -R root:root /usr/lib/icecat/browser/extensions/html5-video-everywhere@lejenome.me
sudo find /usr/lib/icecat/browser/extensions/html5-video-everywhere@lejenome.me -type d -exec chmod 0755 \{\} \;
sudo find /usr/lib/icecat/browser/extensions/html5-video-everywhere@lejenome.me -type f -exec chmod 0644 \{\} \;
```

**Comment by suedi** [comment]
I ran your suggested commands but with the minimal permissions.

Now it works fine!

Thank you.

closing...
