### ISSUE TITLE
Embeded videos automatically play in background when loaded

### ISSUE THREAD

**Issue by lsevero** [tikservices/html5-video-everywhere#77]
This add-on in firefox are creating 2 instances of the embeded youtube videos. I am experiencing it on some websites like reddit.
One of them are playing automatically when loaded in background, and it is impossible to pause them because you don't have the controls. The second one is fine and visible on the website, but if you want to see it you will have listen to the audio of both instances.

**Comment by gfody** [comment]
same issue here, Firefox 51.0.1 (64-bit)

**Comment by lsevero** [comment]
I'm also using Firefox 51.0.1 (64-bit), forgot to add.

**Comment by lejenome** [comment]
It's a race condition caused by YouTube trying to play the video even if
the add-on has removed the YouTube Video Player.

I tried to fix it many times but with no success because It's very hard to
reproduce and to track.

**Comment by joachim42** [comment]
Today I encountered the same behaviour for the first time, so I did some experimenting. So far, for me the problem occurs only on a few videos which consist mainly of static pictures.

Examples: 
https://www.youtube.com/watch?v=AfelCtfFLpM
https://www.youtube.com/watch?v=EdzXDPZPBfw
https://www.youtube.com/watch?v=hMYd8AOxNC8

For the above three, I could reproduce it every time.

I wonder if it might depend on the OS and/or Firefox version. I never noticed the problem until now - two days after updating from Mac OS 10.6.8 Snow Leopard to 10.11.6 El Capitan, and Firefox from 48.0.2 to 51.0.1.

**Comment by ghost** [comment]
Ditto. I have this same issue. I needed to disable the add-on. It was driving me nuts. I hope @lejenome can fix this.

**Comment by laodzu** [comment]
Same problem here. Debian Stretch and Firefox ESR 45.7.0.  Disabling the plugin seems to fix the issue.

**Comment by strypey** [comment]
I'm also having this same issue on two different computers:
A laptop running Linux Mint 17.3 and Firefox 53.0.3 (64-bit), and a desktop running Trisquel 7 and ABrowser 52.02 (64-bit). I haven't noticed whether it only affects embeds from YT or not.

**Comment by strypey** [comment]
GNU Social embeds videos when the YT links are included in a post. I can play a video, control it, and clicking the YT button next to the fullscreen button opens the video on YT in its own window, and stops the video in the embed. It works very reliably. I don't remember ever clicking the YT button and the video not stopping. Maybe the code/ API or whatever it is that stops the embed on GNU Social, could be studied for a way to make sure the same thing happens in HTML5 Video Everywhere?
