### ISSUE TITLE
Adds extra sound streams at kde/gnu/linux

### ISSUE THREAD

**Issue by Svetlana-T** [tikservices/html5-video-everywhere#78]
![screenshot2](https://cloud.githubusercontent.com/assets/9674923/23583864/1f12b684-01a4-11e7-8ed3-41f3af2b6a0a.jpg)

See at the right - a video sound stays there from a video which I played a few minutes ago, and I do not see how to turn it off... Debian Jessie KDE GNU/Linux, Firefox ESR 45.7.0, HTML5 Video Everywhere! 0.3.4

 I have to mute them by hand to be able to listen to new items.

**Comment by lejenome** [comment]
The addon use only the standard Web elements `<video>` of Firefox. This
issue seems to be Firefox specific.

Try to report the bug To Mozilla Bugzilla.

On Sun, Mar 5, 2017 at 3:05 AM, Svetlana Tkachenko <notifications@github.com

**Comment by lejenome** [comment]
I'm closing this issue. If you are still having this issue (only when the extension is enabled), please reopen the issue.
