### ISSUE TITLE
Port to Web Extionsions to work with Firefox 57 :S

### ISSUE THREAD

**Issue by Teyro** [tikservices/html5-video-everywhere#87]
Hi there,

Is there a plan to port this addon to the new API called "Web Extensions" ? Because in Firefox 57 html5videoeverywhere wont work anymore :(

**Comment by lejenome** [comment]
Yes, work already in progress. check [webextension branch](https://github.com/lejenome/html5-video-everywhere/tree/webextension).

**Comment by lejenome** [comment]
The latest release is a complete port to WebExtension API. Some features are still missing.
