### ISSUE TITLE
One video from youtube does not opens

### ISSUE THREAD

**Issue by blackwarthog** [tikservices/html5-video-everywhere#88]
This video don't opens: https://www.youtube.com/watch?v=ejE6CX8jZhI

Other videos works fine
I've used IceCat 52.1.0 and HTML5-video-everywhere from master branch, cookis disabled

![2017-08-19 21-41-19](https://user-images.githubusercontent.com/5143743/29487650-3aec9ce2-8527-11e7-8591-523555823616.png)

**Comment by lejenome** [comment]
Support for YouTube was fixed on latest release
