### ISSUE TITLE
Add support for LEGO.com

### ISSUE THREAD

**Issue by DoomTay** [tikservices/html5-video-everywhere#89]
Example video: https://www.lego.com/en-us/starwars/videos/the-rathtar-escape-0bb49c32c9ed4e2fa1b2ab9ebcd3dd57

Their own setup tends to be somewhat buggy when it comes to longer videos

Setting this up is actually pretty simple. The relevant data is stored in a JSON in the iframe. If this JSON is stored in a variable called vidData, then code like this can be used to put the video URL together

```javascript
var vidData = JSON.parse(document.querySelector("div[video]").getAttribute("video"));
var domain = document.documentElement.getAttribute("data-video-progressive-url");

var compiledURL = "";

if(!vidData.NetStoragePath) compiledURL = domain + "public/" + vidData.ItemId.substr(0,2) + "/" + vidData.ItemId.substr(2,2) + "/" + [vidData.ItemId,vidData.VideoId,vidData.Locale,vidData.VideoVersion].join("_");
else compiledURL = domain + "public/" + vidData.NetStoragePath + "/" + [vidData.ItemId,vidData.VideoId,vidData.Locale,vidData.VideoVersion].join("_");

var newVideo = document.createElement("video");
newVideo.style.width = newVideo.style.height = "100%";
newVideo.poster = vidData.CoverImageUrl;
newVideo.controls = true;
newVideo.autoplay = vidData.AutoPlay;

var types = [".mp4",".webm"];

for(var i = 0; i < types.length; i++)
{
	var source = document.createElement("source");
	source.src = compiledURL + "_" + quality + types[i];
	newVideo.appendChild(source);
}

var wrapper = document.querySelector("div.video-wrapper");
wrapper.innerHTML = "";
wrapper.appendChild(newVideo);

document.body.style.backgroundColor = "black";
```

..where `quality` is 2560, 1536, 1024, 512 or 256, which are the internal numbers for 720p, 540p, 360p, 270p and 180p respectively

**Comment by lejenome** [comment]
Thank you for the detailed explanation. Support for Lego.com has been added to the [webextension branch](https://github.com/lejenome/html5-video-everywhere/tree/webextension). This branch is still WIP. Hopefuly with the next few days, a new version will be released with Lego.com support.
