### ISSUE TITLE
[Firefox 55.0.3] YouTube freeze in 0.4.2; "Disable on YouTube" doesn't work

### ISSUE THREAD

**Issue by proninyaroslav** [tikservices/html5-video-everywhere#90]
Hello. After upgrading to 0.4.2, I'm watching friezes on YouTube. The script in the screenshot is guilty, Firefox offers to stop it. Also, I tried to disable the plugin for YouTube in the settings, ("Disable on YouTube" option), but after exiting the settings it reset the flag back by default.

![2017-09-28 11-50-38](https://user-images.githubusercontent.com/7840559/30957677-9f32768c-a443-11e7-8f42-0fd5dfd959ad.png)
![2017-09-28 11-51-21](https://user-images.githubusercontent.com/7840559/30957683-a2334e6a-a443-11e7-9c60-1dbe499f404e.png)

**Comment by alekksander** [comment]
both confirmed here

**Comment by lejenome** [comment]
This issue is fixed on the new version v0.4.3. It's now available for public on AMO.
