### ISSUE TITLE
Old video player still plays under the new HTML5 player

### ISSUE THREAD

**Issue by RaineIkari** [tikservices/html5-video-everywhere#91]
I have enabled HTML5-Video-Everywhere on my firefox, but whenever I play Youtube videos the older flash player plays under it and I can hear the audio from that player. The only way to stop it is to reload the page and not click on anything, but even then there is still a risk that an add will play with the reload. Is there anyway around this? A workaround that can address this issue?

**Comment by Kasijjuf** [comment]
Have you tried removing the Flash browser plug-in?

**Comment by RaineIkari** [comment]
This has worked! Thank you!
