### ISSUE TITLE
firefox html5 dont work on youtube.

### ISSUE THREAD

**Issue by tassos38** [tikservices/html5-video-everywhere#94]
Hallo all,

till last week everything works well. but since then it dont work anymore on youtube.
on other platforms like kinox.to or view4u.co I have to refresh the side sometimes 3 or 4 times till I get the button to play, also on openload.co, rapidvideo.com and streamango.com alot of problems.

on vimeo the html5 dont work!

it works stable on vidzi.tv.

I didnt install any apps and I also dont change settings or something like that, in the last 2 weeks.

do somebody have a tip for me, how I can get it functioned.

but a big thank you, for the good work you did till yet.
greets tassos

**Comment by lejenome** [comment]
This issue should be fixed on the latest version released few minutes ago.

Please update to the latest version and check if the issue is fixed.

**Comment by tassos38** [comment]
thank you very much for the fast responce. it works again now.
very good job you do here. tyvvvvvm :)
